spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sustc  # change this to your own jdbc url
    username: postgres  # change this to your own username (avoid using a superuser)
    password: 123456  # change this to your own password

---

benchmark:
  data-path: data
  student-mode: true
